#pragma once

typedef enum {
    FDPS_EXCHANGE_LET_A2A,
    FDPS_EXCHANGE_LET_P2P_EXACT,
    FDPS_EXCHANGE_LET_P2P_FAST,
} FDPS_EXCHANGE_LET_MODE;

typedef enum {
    FDPS_MAKE_LIST,
    FDPS_MAKE_LIST_FOR_REUSE,
    FDPS_REUSE_LIST,
} FDPS_INTERACTION_LIST_MODE;

typedef enum {
    FDPS_LONG_NO_CUTOFF,
    FDPS_LONG_CUTOFF,
    FDPS_LONG_SCATTER, // new for P^3T
    FDPS_LONG_CUTOFF_SCATTER, // new for P^3T + PM
    FDPS_LONG_SYMMETRY,
    FDPS_SHORT_GATHER,
    FDPS_SHORT_SCATTER,
    FDPS_SHORT_SYMMETRY,
} FDPS_SEARCH_MODE;

typedef enum {
    FDPS_FORCE_TYPE_LONG,
    FDPS_FORCE_TYPE_SHORT,
} FDPS_FORCE_TYPE;

typedef enum {
    FDPS_CALC_DISTANCE_TYPE_NORMAL = 0,
    FDPS_CALC_DISTANCE_TYPE_NEAREST_X = 1,
    FDPS_CALC_DISTANCE_TYPE_NEAREST_Y = 2,
    FDPS_CALC_DISTANCE_TYPE_NEAREST_XY = 3,
    FDPS_CALC_DISTANCE_TYPE_NEAREST_Z = 4,
    FDPS_CALC_DISTANCE_TYPE_NEAREST_XZ = 5,
    FDPS_CALC_DISTANCE_TYPE_NEAREST_YZ = 6,
    FDPS_CALC_DISTANCE_TYPE_NEAREST_XYZ = 7,
} FDPS_CALC_DISTANCE_TYPE;

typedef enum {
    FDPS_BC_OPEN,
    FDPS_BC_PERIODIC_X,
    FDPS_BC_PERIODIC_Y,
    FDPS_BC_PERIODIC_Z,
    FDPS_BC_PERIODIC_XY,
    FDPS_BC_PERIODIC_XZ,
    FDPS_BC_PERIODIC_YZ,
    FDPS_BC_PERIODIC_XYZ,
    FDPS_BC_SHEARING_BOX,
    FDPS_BC_USER_DEFINED,
} FDPS_BOUNDARY_CONDITION;

typedef enum {
    EXCHANGE_LET_A2A,
    EXCHANGE_LET_P2P_EXACT,
    EXCHANGE_LET_P2P_FAST,
}EXCHANGE_LET_MODE;

