#pragma once

typedef enum {
   FDPS_BC_OPEN,
   FDPS_BC_PERIODIC_X,
   FDPS_BC_PERIODIC_Y,
   FDPS_BC_PERIODIC_Z,
   FDPS_BC_PERIODIC_XY,
   FDPS_BC_PERIODIC_XZ,
   FDPS_BC_PERIODIC_YZ,
   FDPS_BC_PERIODIC_XYZ,
   FDPS_BC_SHEARING_BOX,
   FDPS_BC_USER_DEFINED,
} FDPS_BOUNDARY_CONDITION;

typedef enum {
   FDPS_MAKE_LIST,
   FDPS_MAKE_LIST_FOR_REUSE,
   FDPS_REUSE_LIST,
} FDPS_INTERACTION_LIST_MODE;
