echo "#pragma once"
echo ""
echo "#define $1"
echo ""
echo "#include <treepm_header.h>"
echo "#include <pm_parallel.h>"
echo "#include <particle_mesh_class.hpp>"
echo ""
echo "namespace ParticleSimulator{"
echo "namespace PM = ParticleMesh;"
echo "}"
