check:
	make -C exchangeParticle CCC="$(CCC)" CFLAGS="$(CFLAGS)" PS_PATH="$(PS_PATH)"

clean:
	rm -f *~
	make -C exchangeParticle clean

distclean:
	rm -f *~
	make -C exchangeParticle distclean

allclean:
	rm -f *~
	make -C exchangeParticle allclean

